import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by Next App" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to Next TS Application
        </h1>
        <br />
        <h2>
          This is Bharat Sharma
        </h2>
      </main>
    </div>
  )
}
